experiment_name: toy
executing_institution: Ouranos
path_output: /network/projects/amlrt_internships/ouranous/data/output_toy
path_regridding_weights: /network/projects/amlrt_internships/ouranous/regridding_weights
path_gcm_data: /network/projects/amlrt_internships/ouranous/data/GCMs
path_emission_data: /network/projects/amlrt_internships/ouranous/data/GHGs
path_crcm_data: /network/projects/amlrt_internships/ouranous/data/MRCC5-CMIP6

# Global parameters
tile_size: 608
coarsen_factor: 8
apply_normalization: false
normalization_start_date: "2014-11-01"
normalization_end_date: "2015-02-01"

# GCM preprocessing
path_gcm_preprocessing: /network/projects/amlrt_internships/ouranous/data/preprocessed_toy/gcm_preprocessing
preprocessing_simulations:
  -
    - CNRM-ESM2-1
    - historical
    - r1i1p1f2
  -
    - CNRM-ESM2-1
    - ssp245
    - r1i1p1f2
gcm_preprocessing_start_datetime: "2014-11-01"
gcm_preprocessing_end_datetime: "2015-02-01"
gcm_preprocessing_variables:
  - hus
  - psl
  - ta
  - ua
  - uas
  - vas
  - va
  - zg
gcm_preprocessing_allow_overwrite: false

# CRCM preprocessing (uses preprocessing_simulations from GCM preprocessing)
path_crcm_preprocessing: /network/projects/amlrt_internships/ouranous/data/preprocessed_toy/crcm_preprocessing
crcm_preprocessing_start_datetime: "2014-11-01"
crcm_preprocessing_end_datetime: "2015-02-01"
crcm_preprocessing_variables:
  - tas
  - pr
  - uas
  - vas
crcm_preprocessing_allow_overwrite: false

# DataLoader parameters
gcm_training_variables:
  - zg850
  - zg700
  - zg500
  - hus850
  - hus700
  - hus500
  - ta850
  - ta700
  - ta500
  - uas
  - ua850
  - ua700
  - ua500
  - vas
  - va850
  - va700
  - va500
  - psl
crcm_training_variables:
  - tas
training_periods:
  -
    - "2014-11-01"
    - "2014-12-01"
validation_periods:
  -
    - "2014-12-02"
    - "2015-01-01"
test_periods:
  -
    - "2015-01-02"
    - "2015-02-01"

# Training parameters
training_batch_size: 2
unet_kernel_size: 3
unet_initial_num_of_hidden_channels: 64
unet_depth: 3
unet_reduction_ratio: null
learning_rate: 0.01
weight_decay: 0.001
mse_loss_weight: 1.0
ssim_loss_weight: 0.0
nb_of_epochs: 10
num_workers: 2
num_threads: 2
training_device: cuda

debug_crcm_figures:
  - ["CNRM-ESM2-1", "historical", "r1i1p1f2", "tas", 2000, 1, 2]
  - ["CNRM-ESM2-1", "ssp245", "r1i1p1f2", "uas", 2025, 7, 24]
debug_gcm_figures:
  - ["CNRM-ESM2-1", "historical", "r1i1p1f2", "ta850", 2000, 1, 2]
  - ["CNRM-ESM2-1", "ssp245", "r1i1p1f2", "psl", 2025, 7, 24]
