processDescription:
  process:
    outputs:
      - id: HRDPS_P_PR_SFC
        formats:
          - mediaType: application/x-netcdf
      - id: HRDPS_P_TT_10000
        formats:
          - mediaType: application/x-netcdf
      - id: HRDPS_P_UUC_10000
        formats:
          - mediaType: application/x-netcdf
      - id: HRDPS_P_VVC_10000
        formats:
          - mediaType: application/x-netcdf
