config:
  class: File
  path: ../../configs/downscaling/downscaling_inference_rdps_to_hrdps.yaml
inputs_dir:
  class: Directory
  path: ../../inputs/
logs_dir:
  class: Directory
  path: ../../logs/
figures_dir:
  class: Directory
  path: ../../figures/
