config:
  class: File
  path: ../../configs/downscaling/downscaling_rdps_to_hrdps_cwl.yaml # when using weaver use fileserver path
  format: "https://www.iana.org/assignments/media-types/application/yaml"
input_data:
  class: Directory
  path: ../../inputs # directory containing the input NetCDF files, preserving their parent folder structure (e.g., 202405/2024050100_007.nc)
